###
POST http://localhost:3005/register
Content-Type: application/json

{
    "username": "Agastin",
    "password": "Agastin@2001",
    "email": "agastinmellimi2001@gmail.com",
    "gender": "MALE"
}

###
GET http://localhost:3005/

###
POST http://localhost:3005/login
Content-Type: application/json

{
    "username": "Agastin",
    "password": "Agastin@2001",
    "email": "agastinmellimi2001@gmail.com",
    "gender": "MALE"
}

###
GET http://localhost:3005/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFnYXN0aW4iLCJpYXQiOjE3MDg3MDQxNjF9.arxD6WG2CGCPcWh9YxEbm_TUrcCMQ39TJEAbdNUmRrE

###
POST http://localhost:3005/children
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFnYXN0aW4iLCJpYXQiOjE3MDg3MDQxNjF9.arxD6WG2CGCPcWh9YxEbm_TUrcCMQ39TJEAbdNUmRrE

{"name": "SANTHOSH DHANAM", "gender": "MALE"}

###
POST http://localhost:3005/attendance
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFnYXN0aW4iLCJpYXQiOjE3MDg3MDQxNjF9.arxD6WG2CGCPcWh9YxEbm_TUrcCMQ39TJEAbdNUmRrE

{
    "array": [
  {"childId": 1, "date": "2024-02-04",  "present": false}, 
  {"childId": 2, "date": "2024-02-04",  "present": true}, 
  {"childId": 3, "date": "2024-02-04",  "present": true}, 
  {"childId": 4, "date": "2024-02-04",  "present": false}, 
  {"childId": 5, "date": "2024-02-04",  "present": true}, 
  {"childId": 6, "date": "2024-02-04",  "present": true}, 
  {"childId": 7, "date": "2024-02-04",  "present": true},
  {"childId": 8, "date": "2024-02-04",  "present": true}, 
  {"childId": 9, "date": "2024-02-04",  "present": true},
  {"childId": 10, "date": "2024-02-04",  "present": true},
  {"childId": 11, "date": "2024-02-04",  "present": true}
]
}